### ISSUE TITLE
Request feature

### ISSUE THREAD

**Issue by Linuxfy** [kurozenzen/r34-react#4]
Block source and blacklist tags please

**Comment by kurozenzen** [comment]
Block source meaning you want to exclude say all posts from `twitter` or `hentai-foundry`?

This can be done in a hacky way currently: Enter `source:*twitter*` in the input and use the "-" modifier (see below)
Needs nicer UX though. Added to Todo list.

blacklist tags are already there. Try clicking the "+" in the input. That cycles through the modifiers

"+" means: posts must have the tag
"-" means: posts are not allowed to have the tag
"~" means: posts must have one of all the ~ tags (you need 2 for it to work properly)

If you meant something else please let me know.
