### ISSUE TITLE
Key features broken

### ISSUE THREAD

**Issue by Kenyonfair712** [kurozenzen/r34-react#46]
**Describe the bug**

The auto fill for tags- is broken
Search results loop after about 20 results 
Sorting is broken and only shows by date

**Screenshots**

**Device**
The device you saw the bug on.

Google chrome for I-pad mini

**Additional information**

**Comment by kurozenzen** [comment]
Thanks for the clear issue report. This enabled me to fix it very quick. Let me know if anything else does not work still.
