### ISSUE TITLE
Small images size on non-chrome  browser

### ISSUE THREAD

**Issue by Linuxfy** [kurozenzen/r34-react#5]
I try this on Microsoft Edge, Kiwi Browsrr, UC-Browser, Huawei Native Browser and images and website is not load properly.
Google Chrome having no issue

Images
https://ibb.co/JFMQkCM

**Comment by kurozenzen** [comment]
yikes. I will see what I can do. Probably because they dont support the new css attributes `aspect-ratio` and `object-fit`.

That's just a quick guess though.

Thanks for bringing it to my attention.

**Comment by kurozenzen** [comment]
I made the css more robust and added some compatibility if any of the fancy new stuff is not supported. The page might not look entirely as expected in some browsers but it should be usable now.

I tested with edge and kiwi. Not sure about the others. (I did some very light testing. I might have missed some things)

Let me know if you catch any other issues.

**Comment by Linuxfy** [comment]
Thank for uodate. I tested all browser i try previously and it all working 👍

**Comment by kurozenzen** [comment]
Great to hear that! Have a nice day.
