### ISSUE TITLE
Alternative way to sync settings/preferences

### ISSUE THREAD

**Issue by Yimellovzski** [kurozenzen/r34-react#60]
**Describe the feature**
Maybe we could have another option or method to sync options between browsers or devices that is not though logging into a Google account, some people may not have a google account because of security purposes / privacy related concerns, and I think implementing an alternative option like pasting a custom url with all the cookies of the site onto another device/browser (i.e. SearX's Preference URL) could make it (slightly) easier for people so they don't have to retype the tags, set the preferences/themes every time they log on to another browser within the same device or from a different one. 

**Additional Information**
Just don't wanna have all linked to Google to be entirely honest lol, I'm open to other alternatives/ideas!

**Comment by kurozenzen** [comment]
Thanks for the feedback.

I can probably provide some different sign up methods from the list below with relatively small effort. I will look into that.

![image](https://user-images.githubusercontent.com/44543171/187069462-846c3360-7ece-4d15-8c2d-c57da38b7c41.png)

That being said, the url thing might be a bit harder to build. It's a very nice idea though.

**Comment by kurozenzen** [comment]
I built a quick prototype for email only authentication on [kurosearch.com](https://kurosearch.com/). Would appreciate some feedback.

Do you think signing up with email is acceptable? Or would you prefer a way to sync without an account?

**Comment by Yimellovzski** [comment]
Just visited [your site](https://kurosearch.com/), and I have to mention that the UI is much cleaner than the React one. As far as signing up with email is concerned, I wouldn't say it's the best practice, but it's a step nonetheless. Signing with a GitHub account could be another option, though I don't feel like many people would want their account linked to a nsfw website. Syncing without an account would make it easier since you wouldn't even have to have any kind of email address to be able to port preferences to another device. Maybe a system where stored personal cookies (containing all the settings and tags) can be extracted and sent to another browser/device through a file or URL could be implemented.

PS: The sign-up option seems to be non-functional in my browser

**Comment by kurozenzen** [comment]
ah just found out that it can't handle a few error cases well....

maybe I can put the tags in the url. THat wold make it easy to port a search from one device to another.

I will do a bit of investigation.

**Comment by kurozenzen** [comment]
Kurosearch.com supports this now. Adding it to rule34react is too much work atm...
