### ISSUE TITLE
Ignore tags

### ISSUE THREAD

**Issue by RevolverSnake** [kurozenzen/r34-react#62]
**Describe the feature**
It would be great to exclude some tags forever like if I don't want to watch overdramatically fat women or whatever

**Additional Information**
Some menu in the settings to add tags that we'll be ignored in the future

**Comment by arynthernium** [comment]
By default, the site stores tags you enter in localStorage, which means they'll persist throughout reloads and won't clear unless you remove them. In your case, leaving "overweight" or similar tags in the list in negative mode will exclude all posts with those tags.

Negative tags can be added by switching the tag mode. Clicking on the "+" on the left of the search bar will cycle it through to either a "-" or a "~". The "-" will add tags in negative mode, which will exclude all posts that have them, and will show that with a strikethrough in the tag list.

**Comment by kurozenzen** [comment]
I think this functionality is nicely covered by supertags. Create an account and you will be able to group multiple tags together to so called "supertags" that way you can easily block lots of tags with a single one.

**Comment by RevolverSnake** [comment]
I see, worth to try
