### ISSUE TITLE
Website doesnt work anymore. 

### ISSUE THREAD

**Issue by Ohichist** [kurozenzen/r34-react#63]
**Describe the bug**
When I'm trying to search smthing, nothing pops up ``even if you click on search``. 
(Btw my Wi-Fi is working well) 

**Screen:**
![Screenshot_20221130_222114_Ecosia](https://user-images.githubusercontent.com/119549314/204943513-e13f9630-1bb7-4ec1-8819-ee43aaa8d9d5.jpg) 

**Device**
Samsung A52 5G

Thanks!

**Comment by Yimellovzski** [comment]
It doesn't work for me either!

**Comment by markstone3710** [comment]
Somehow it doesn't work for me too, maybe it's down?

**Comment by REinstatedJedi** [comment]
Go to preferences and scroll all the way down to backend and change It to adaptable that's what worked for me

**Comment by kurozenzen** [comment]
I changed the default backend you should be good now.
