### ISSUE TITLE
searching tags

### ISSUE THREAD

**Issue by tillertheshark** [kurozenzen/r34-react#65]
when searching a title and i press add, there isnt a icon beside the tag, and when i press search nothing happens, i would reset the browser like it said to if its glitched, but im not entirely sure how to do that which is why im here.

![image](https://user-images.githubusercontent.com/119712335/205414399-f93ddbaa-e439-4dfe-9097-654f9d1c5cb3.png)
![image (1)](https://user-images.githubusercontent.com/119712335/205414404-ec78ba2c-5733-4ae9-82a3-c85cd501389f.png)

**Comment by REinstatedJedi** [comment]
Go to preferences and scroll all the way down to backend and change It to adaptable that's what worked for mr

**Comment by tillertheshark** [comment]
oh, thanks man

**Comment by tillertheshark** [comment]
it actually worked surprisingly

**Comment by REinstatedJedi** [comment]
No problem👍

**Comment by tillertheshark** [comment]
thanks for letting me continue to watch porn XD, not something i figured
i'd say today

**Comment by kurozenzen** [comment]
Sorry about this. SHould be fixed now.

**Comment by tillertheshark** [comment]
Awesome, thanks!
