### ISSUE TITLE
Rule34 react not working!

### ISSUE THREAD

**Issue by Zekethezaka** [kurozenzen/r34-react#66]
**Describe the bug**
Simply put; I can’t use tags on rule34 react, therefore, I cannot use it.

**Screenshots**
It just doesn’t work

**Device**
Apple; Safari

**Additional information**
Tags just aren’t showing up when I search them, or when I type them in myself.

**Comment by arynthernium** [comment]
Currently, the Heroku backend is down. That's the default one selected. Changing the backend to Adaptable in Preferences (near the bottom of the list) should fix this issue for now.

**Comment by kurozenzen** [comment]
Sorry about this. Some of the backends were taken down. It should be fixed now. Let me  know if it isn't and I will have another look.
