### ISSUE TITLE
Certain tags not working

### ISSUE THREAD

**Issue by RaccoonHours** [kurozenzen/r34-react#7]
Any tag that uses a '/' such e.g. 'male/female' 'male/male' doesn't seem to be working, sorry for the trouble♡ keep up your amazing work!!

**Comment by kurozenzen** [comment]
On it!

**Comment by kurozenzen** [comment]
It was a quick fix. I included it in today's update. Don't worry about reporting bugs. I'd rather fix them then leave them.
