### ISSUE TITLE
what's wrong with website?

### ISSUE THREAD

**Issue by arguilia** [kurozenzen/r34-react#70]
![Screenshot_2022-12-10-12-56-14-384_com android chrome](https://user-images.githubusercontent.com/120244015/206840059-b836549e-5788-4f32-9397-4e3710f383ab.jpg)
**Describe the bug**

**Screenshots**

**Device**
The device you saw the bug on.

**Additional information**

**Comment by kurozenzen** [comment]
Talked about this on discord but I will respond here as well. My servers were taken down and I had to find another solution. Took a while but now everything should be back online.
