### ISSUE TITLE
"Show Comments" option does not seem to work.

### ISSUE THREAD

**Issue by Yimellovzski** [kurozenzen/r34-react#73]
**Describe the bug**
when clicking 'show comments' under a post (must have 'show post details' toggled as well), it seems to return an error page.

**Video**

https://user-images.githubusercontent.com/45341995/213825282-a35de74b-73f6-468b-a3d4-56f52dc0a1bc.mp4

**Device**
OS: Pop!_OS 22.04 LTS
Browser: Qutebrowser v2.5.2 (Python/Chromium)

**Comment by kurozenzen** [comment]
I know. Talked about this on discord already. It's on the todo list. Sadly, I don't have much time currently.

**Comment by Yimellovzski** [comment]
It's understandable, my apokogies for opening a redundant issue, feel free to close it.

**Comment by kurozenzen** [comment]
I just fixed this :) Might take a few hours to be released though.
