### ISSUE TITLE
Random Post

### ISSUE THREAD

**Issue by oebsworth** [kurozenzen/r34-react#74]
**Describe the feature**
A clear and concise description of what you want.

Rule 34 has a feature where you can click a button and it will show you a random post. Good for finding new stuff to look at/ new kinks to explore.

**Additional Information**

**Comment by Yimellovzski** [comment]
Might be hard for the dev to implement, as R34-React's search is based on tags, not post id's. I'm not a web developer however, might be doable!

**Comment by kurozenzen** [comment]
Its definitely doable. I'll add it to the todo list and play around with it.

**Comment by oebsworth** [comment]
I might be wrong but I thought it was based off post ids, I'll have a play
my end too and let you know what I find.

**Comment by oebsworth** [comment]
Nevermind completely misread that message *facepalm*. Yeah I wouldn't know
where to start with react so I'll leave it up to you.

**Comment by kurozenzen** [comment]
You can access a single post by id on their api. The ids are steadily increasing. So the oldest post has id 1 and the last one probable something around 5000000. I may need to guess that and generate a random number in that range. With that i can then request a random post

**Comment by oebsworth** [comment]
Yeah that was exactly what I was thinking. Might be a way to fetch all
posts without fetching their data, or maybe use an rss feed to find out how
many posts exist. Or as you say just hard code it and update it once a
month or smthn. Idk how react works so that ends upto you.

**Comment by oebsworth** [comment]
Just looking at the api if you parse from xml then the post count is one of
the first things that comes up.
<posts count="6578876" offset="0">

**Comment by oebsworth** [comment]
Managed to get the post count with the library XML2JSON, used an xhr for
the req data
[image: image.png]
https://github.com/abdolence/x2js
