### ISSUE TITLE
loader / calling error

### ISSUE THREAD

**Issue by WRA1TH-n-vengence** [kurozenzen/r34-react#75]
fails to load anything, recall any items, etc.

**Screenshots**
![image](https://user-images.githubusercontent.com/72632521/214220537-22f82af0-7638-4b41-9db4-b197d9dc003c.png)

**Device**
Dell Chromebook 
**Additional information**
no additional settings, on default. attempted altering settings, no alterations to the error.

**Comment by kurozenzen** [comment]
Still happening? I did some disruptive migrations at that time.

**Comment by WRA1TH-n-vengence** [comment]
![Uploading image.png…]()
still happening, yeah.

**Comment by kurozenzen** [comment]
can you try resetting the application from the settings? (its the last button at the bottom) You will have to log in again but all your data will be saved.

**Comment by Mobshiz** [comment]
It's still not working after changing backends and resetting everything. tried on another browser still, but no posts are shown. The login still works.

**Comment by WRA1TH-n-vengence** [comment]
same on my end.

**Comment by artyomof** [comment]
i have the same problem at all

**Comment by kurozenzen** [comment]
most likely this is due to issues on www.rule34.xxx. If they are having issues with their apis then my apps wont work. Usually, they resolve them quite fast though...
