### ISSUE TITLE
Supertags have disappeared 

### ISSUE THREAD

**Issue by Hrshl7** [kurozenzen/r34-react#76]
**Bug description**
Despite being connected and using the same device, all supertags have been deleted and creating a new supertag doesn't list it in the supertag section. 

**Device**
Xiaomi Redmi Note 11 on chrome.

**Additional information**
Tried to connect on Opera but bug is the same.

**Comment by kurozenzen** [comment]
Hey thanks for reporting. This was an error on my side😐. I fucked up the security settings on the DB. Now you don't have permission for your own supertags. Sorry. Will fix it today or tomorrow

**Comment by kurozenzen** [comment]
okay should be fixed
