### ISSUE TITLE
Search tags and failures to show anything.

### ISSUE THREAD

**Issue by Mobshiz** [kurozenzen/r34-react#77]
**Describe the bug**
This issue has been reported before but it's still not resolved. The whole website doesn't call/show any content. When writing tags it doesn't show up. Tried changing backends but still. The login works perfectly but the whole website is completely useless. One strange thing. I tried the old and other versions (Kurosearch) and it has the same problem. Made me think maybe it was the backends. Either way, thank you for fixing other issues hopefully this one too.

**Screenshots**
![Screenshot_20230214_201357_DuckDuckGo](https://user-images.githubusercontent.com/123793423/218929787-8cfb27e6-5a2f-4122-8ea0-4c26a447f70a.png)
![Screenshot_20230130_223232_DuckDuckGo](https://user-images.githubusercontent.com/123793423/218929790-949e06e3-f93f-41a0-b631-f0e946f7407c.png)

**Device**
Samsung Galaxy S9

**Additional information**
Mainly Using Duckduckgo browser but same thing with chrome and google.

**Comment by Mobshiz** [comment]
> sorry about that, I was quite busy in february... Does it still happen? I fixed some stuff lately.

It was fixed for a bit but now it's still not working, also in the new site your working on

**Comment by kitty33354** [comment]
still does not work

**Comment by kurozenzen** [comment]
its an issue with www.rule34.xxx which is where all the images come from. If they experience issues my apps are affected as well.

It happens from time to time but they are fast at fixing things.
