### ISSUE TITLE
A couple quality of life enhancements that would be pretty cool I think

### ISSUE THREAD

**Issue by AnotherAnonymousNerd** [kurozenzen/r34-react#78]
Couple minor (ish) quality of life changes that would be very nice
1. Undo remove tab button
2. (No idea how hard this is, I haven't worked with react, so this might be very difficult) make the back button go through previous searches
3. Maybe some way to group tags, maybe by type (i.e. separate them into distinct sections for normal, negative, and whatever the ~ one is
4. Automatically make the tags for anything related to zoophilia and pedophilia be negative (or even better, automatically filter them out by default 😉) - this one is a bit esoteric, but pedos/zoos deserve it

**Comment by kurozenzen** [comment]
1. Is something I have tried already its super nice. Buuuut its a pain to make it work on mobile devices.
3. Is partially covered by so called super tags. But there is some work still ongoing
4. You can filter them out yourself. It would be pretty tedious to find all the tags related to those topics...

**Comment by kurozenzen** [comment]
Thanks for the feedback though. I will try again to make 1 work and prioritize the improvements to 3 a bit higher.

**Comment by AnotherAnonymousNerd** [comment]
If I were to go through every single tag on r34 and find every one that was related to zoo/pedo shit would you consider it?

**Comment by kurozenzen** [comment]
I would make a preference that you can easily turn on like switching the theme 🙂

**Comment by kurozenzen** [comment]
Would that satisfy your needs?

**Comment by AnotherAnonymousNerd** [comment]
That'd be perfect, thanks. I'll start working on the list now

**Comment by kurozenzen** [comment]
Awesome thanks for your help

**Comment by kurozenzen** [comment]
I will implement them first in on kurosearch.com

Less people use that site and I can break things easier there without getting a million complaints

**Comment by AnotherAnonymousNerd** [comment]
```json
[
  "zoophilia",
  "zoo",
  "feral",
  "feral_on_feral",
  "feral_penetrating",
  "feral_penetrated",
  "feral_on_female",
  "feral_on_human",
  "feral_penetrating_feral",
  "feral_penetrating_anthro",
  "feral_penetrating_human",
  "feraligatr",
  "bestiality",
  "bestiality_impregnation",
  "bestiality_tattoo",
  "bestiality_girlfriend_catalog",
  "bestiality_maniax!",
  "bestiality_vitamin",
  "bestiality_pregnancy",
  "bestiality_marriage",
  "bestiality\r\nnelson",
  "zoophilia",
  "zoophilia\r\nbody_tearing",
  "zoophilia\t",
  "zoophilia\\r\\nbody_tearing",
  "zoophilia\\r\\n",
  "zoophilia\\r\\n\\r\\n",
  "zoophilia\r\nferal",
  "zoophilia\\r\\nai_generated",
  "zoophilia?",
  "anthro_on_feral",
  "dominant_feral",
  "animal",
  "young",
  "younger_female",
  "younger_male",
  "younger_brother",
  "younger_futanari",
  "younger_penetrating_older",
  "younger_dom_older_sub",
  "younger",
  "young_woman",
  "lolita_channel",
  "lolita_fashion",
  "lolita_hairband",
  "loli_dragon_(character)",
  "loligagger",
  "lolirock",
  "loliswitch",
  "captive",
  "captured",
  "defeated",
  "rape",
  "sex_slave",
  "no_consent",
  "molestation",
  "non-consensual",
  "non-con",
  "scared"
]
```
Here's what I've found so far, did some searching with the API as well as manual searching through tags shared with the more common bestiality/pedo tags. I also included rape tags, just figured I might as well. Ordered in the json by type, it should be pretty clear where one type stops and another starts so feel free to do whatever with them.

I had to look at a _lot_ of messed up tags to get this list, so I'm gonna go wash my eyes with bleach now. Might get more for the list later.

**Comment by kurozenzen** [comment]
Awesome, I'll try to get it done this weekend.

**Comment by kurozenzen** [comment]
I have some stuff for university that i need to take care of first. But your help has been super 👍

**Comment by AnotherAnonymousNerd** [comment]
Of course man! Take your time, no rush or anything of course. When I create issues I usually think about whether I would want to do what I'm asking for someone else, and if not, I try to do it myself so that it's not too much hassle for the maintainer-- I've ended up getting added as a maintainer for a couple repos because of doing that (can't say which, there's a reason I made this alt :P)

**Comment by AnotherAnonymousNerd** [comment]
Let me know if there's anything else I can do to help out!

**Comment by kurozenzen** [comment]
Experimental update is live on https://kurosearch.com/
I would like to have your opinion.

**Comment by kurozenzen** [comment]
I had to completely rewrite the searching so I am not sure I will port it to r34-react soon. Can I convince you to use kurosearch? If not, please tell me why because those are the things I need to improve.

**Comment by kurozenzen** [comment]
The groups themselves are defined as simple arrays in this file:
https://github.com/kurozenzen/kurosearch/blob/main/src/types/blocking-groups/BlockingGroup.js
(variable is called `BLOCKING_GROUP_TAGS`)

If you feel like we are still missing some tags or groups let me know.

**Comment by AnotherAnonymousNerd** [comment]
Hell yeah, looks great! I'd never heard of kurosearch but tbh I actually prefer the UI. Thanks so much!
(Closing bc not really related to r34r anymore lol)
