### ISSUE TITLE
Searching and Tags are completely broken

### ISSUE THREAD

**Issue by SunDriedPotato** [kurozenzen/r34-react#79]
**Describe the bug**
Previously the images would load inconsistently if at all, usually extremely slow. Now it when entering tags nothing appears, nor does when you press search nothing happens, no results at all.

**Screenshots**

**Device**
Android and Windows 10

**Additional information**

**Comment by kurozenzen** [comment]
This happens from time to time when rule34.xxx itself is struggling. That's where I get my content from and if they are having issues then my app will not be able to get any posts...

Inconvenient but nothing I can do about it... 😢
