### ISSUE TITLE
Page 'selection' 

### ISSUE THREAD

**Issue by RaccoonHours** [kurozenzen/r34-react#8]
Hey it's me again, sorry!

Just wondering how easy it would be to implement a place next to the pages where you can go immediately to a page by typing in the page number. I only ask if say I want to go to page 100, I can only go from 1-3, then 3-5 etc.

I'm seriously blow away with how efficiant and awesome you have been! Sorry for asking so much but I genuinly think that your app is by far the best if it's kind!

One other very large suggestion would be maybe an option of searching other booru's rather than just rule 34, totally understand if you want to keep it just the one though!!

Thanks again!

**Comment by kurozenzen** [comment]
You can already go to a specific page by just typing in a different number in the center box.

Searching other boorus may be possible in the future. A friend of mine made a pretty cool app that supports all boorus ( https://r34.app/) I might be able to use his api and make it work.

**Comment by kurozenzen** [comment]
I will close this. I hope you're okay with that. If you have any questions feel free to reopen or head over to my discord (see about section).
